"""
Configuration migration service for transitioning from single-database to multi-source architecture.
"""
import json
import os
import shutil
from typing import Dict, Any, Literal, Optional
from datetime import datetime
import logging

from app.models.schemas import AgentSettings, AgentSettingsV2, TargetDBConfig, TargetDBConfigV2

logger = logging.getLogger(__name__)

CONFIG_PATH = "config/agent_settings.json"
BACKUP_SUFFIX = ".v1.backup.json"


def detect_config_version(config_dict: Dict[str, Any]) -> Literal["v1", "v2", "unknown"]:
    """
    Detect configuration version.
    
    Note: As of the skills-based architecture, data sources are NEVER stored in
    agent_settings.json. They are always loaded from skills/_data-source.md files.
    
    Returns:
        "v1" if skills-based format (no 'target_db', no 'data_sources', or has deprecated fields)
        "v2" if legacy multi-source format (has 'data_sources' - deprecated)
        "unknown" if unrecognized format
    """
    # If has target_db (old v1), treat as v1 needing cleanup
    if "target_db" in config_dict:
        return "v1"
    
    # If has data_sources (old v2), treat as v2 (deprecated)
    # Note: This is now deprecated - data sources come from skills
    if "data_sources" in config_dict:
        return "v2"
    
    # If has neither, it's the correct skills-based format (treat as v1)
    # This is the expected state: no database config in settings file
    if "llm_config" in config_dict and "vector_config" in config_dict:
        return "v1"
    
    return "unknown"


def migrate_v1_to_v2(settings: AgentSettings) -> AgentSettingsV2:
    """
    Convert legacy single-database config to multi-source format.
    
    Args:
        settings: AgentSettings (v1) with target_db field
        
    Returns:
        AgentSettingsV2 with data_sources array
    """
    logger.info("Migrating configuration from v1 (single-database) to v2 (multi-source)")
    
    # Convert TargetDBConfig to TargetDBConfigV2
    target_db_v2 = TargetDBConfigV2(
        **settings.target_db.model_dump(),
        # source_id will be auto-generated by default_factory
        enabled=True,
        last_synced=None,
        object_count=0
    )
    
    # Create v2 settings with single source
    settings_v2 = AgentSettingsV2(
        data_sources=[target_db_v2],
        primary_source_id=target_db_v2.source_id,
        llm_config=settings.llm_config,
        embedding_config=settings.embedding_config,
        vector_config=settings.vector_config,
        app_meta=settings.app_meta
    )
    
    logger.info(f"Migration complete. Primary source ID: {target_db_v2.source_id}")
    return settings_v2


def save_backup(config_dict: Dict[str, Any], backup_path: Optional[str] = None) -> str:
    """
    Save backup of current configuration.
    
    Args:
        config_dict: Current configuration dictionary
        backup_path: Optional custom backup path
        
    Returns:
        Path to backup file
    """
    if backup_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = CONFIG_PATH.replace(".json", f"{BACKUP_SUFFIX}.{timestamp}")
    
    with open(backup_path, 'w') as f:
        json.dump(config_dict, f, indent=2)
    
    logger.info(f"Configuration backup saved to: {backup_path}")
    return backup_path


def save_migrated_config(settings_v2: AgentSettingsV2, backup_original: bool = True) -> None:
    """
    Save migrated configuration to disk.
    
    Args:
        settings_v2: Migrated AgentSettingsV2 object
        backup_original: Whether to backup the original config (default: True)
    """
    # Load current config for backup
    if backup_original and os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, 'r') as f:
            current_config = json.load(f)
        save_backup(current_config)
    
    # Write new config
    with open(CONFIG_PATH, 'w') as f:
        json.dump(settings_v2.model_dump(exclude_none=True), f, indent=2)
    
    logger.info(f"Migrated configuration saved to: {CONFIG_PATH}")


def auto_migrate_if_needed() -> Literal["v1", "v2", "migrated", "error"]:
    """
    Automatically detect and migrate configuration if needed.
    
    This function should be called on application startup.
    
    Note: As of the skills-based architecture, data sources are NEVER stored in
    agent_settings.json. They are always loaded from skills/_data-source.md files.
    
    Returns:
        "v1": Config is in skills-based format (correct state) - no migration needed
        "v2": Config has deprecated data_sources field (legacy v2)
        "migrated": Config was successfully migrated
        "error": Migration failed
    """
    if not os.path.exists(CONFIG_PATH):
        logger.error(f"Configuration file not found: {CONFIG_PATH}")
        return "error"
    
    try:
        # Load current config
        with open(CONFIG_PATH, 'r') as f:
            config_dict = json.load(f)
        
        version = detect_config_version(config_dict)
        
        if version == "v1":
            # This is the CORRECT state - skills-based configuration
            # No target_db, no data_sources - all data sources from skills directory
            logger.info("✅ Configuration is in skills-based format (v1). Data sources loaded from skills directory.")
            return "v1"
        
        elif version == "v2":
            # Legacy v2 with data_sources - warn but don't fail
            logger.warning("⚠️ Configuration has deprecated 'data_sources' field. This will be ignored.")
            logger.warning("Data sources are always loaded from skills/_data-source.md files.")
            return "v2"
        
        else:
            logger.error("Unknown configuration format. Manual intervention required.")
            logger.error("Expected format: llm_config, embedding_config, vector_config, app_meta")
            return "error"
    
    except Exception as e:
        logger.error(f"Configuration check failed: {str(e)}", exc_info=True)
        return "error"


def rollback_migration(backup_path: Optional[str] = None) -> bool:
    """
    Rollback to previous configuration from backup.
    
    Args:
        backup_path: Path to backup file. If None, finds most recent backup.
        
    Returns:
        True if rollback successful, False otherwise
    """
    try:
        if backup_path is None:
            # Find most recent backup
            config_dir = os.path.dirname(CONFIG_PATH)
            backups = [f for f in os.listdir(config_dir) if BACKUP_SUFFIX in f]
            if not backups:
                logger.error("No backup files found for rollback")
                return False
            backups.sort(reverse=True)  # Most recent first
            backup_path = os.path.join(config_dir, backups[0])
        
        if not os.path.exists(backup_path):
            logger.error(f"Backup file not found: {backup_path}")
            return False
        
        # Restore backup
        shutil.copy(backup_path, CONFIG_PATH)
        logger.info(f"✅ Configuration rolled back from: {backup_path}")
        return True
    
    except Exception as e:
        logger.error(f"Rollback failed: {str(e)}", exc_info=True)
        return False


def get_migration_status() -> Dict[str, Any]:
    """
    Get current migration status and configuration info.
    
    Returns:
        Dictionary with migration status details
    """
    if not os.path.exists(CONFIG_PATH):
        return {
            "status": "error",
            "message": "Configuration file not found",
            "version": "unknown"
        }
    
    try:
        with open(CONFIG_PATH, 'r') as f:
            config_dict = json.load(f)
        
        version = detect_config_version(config_dict)
        
        # Check for backups
        config_dir = os.path.dirname(CONFIG_PATH)
        backups = [f for f in os.listdir(config_dir) if BACKUP_SUFFIX in f]
        
        status_info = {
            "status": "ok",
            "version": version,
            "config_path": CONFIG_PATH,
            "backup_count": len(backups),
            "backups": sorted(backups, reverse=True)[:5]  # Last 5 backups
        }
        
        if version == "v2":
            settings_v2 = AgentSettingsV2(**config_dict)
            status_info["source_count"] = len(settings_v2.data_sources)
            status_info["primary_source_id"] = settings_v2.primary_source_id
        elif version == "v1":
            settings_v1 = AgentSettings(**config_dict)
            status_info["database_name"] = settings_v1.target_db.database_name
            status_info["needs_migration"] = True
        
        return status_info
    
    except Exception as e:
        return {
            "status": "error",
            "message": str(e),
            "version": "unknown"
        }
